spring:
  data:
    mongodb:
      port: 27017
      host: 192.168.4.32
      database: origami-docs-dev
      username: origami-docs
      password: oRD$Fq@i5jE87he
      authentication-database: admin

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    appname: EMAIL-WEBSERVICES
  client:
    fetch-registry: false
    register-with-eureka: false


email:
  correoHost: smtp.office365.com
  correoPort: 587
  correo: tramites.sgd@bomberosguayaquil.gob.ec
  razonSocial: Benemerito Cuerpo de Bomberos
  correoClave: Bcbg.2024+
  rutaArchivos: D:/servers_files/archivos/
  keyFiles: 12345


