spring:
  data:
    mongodb:
      port: 27017
      host: 192.168.4.32
      database: origami-logs-dev
      username: origami-docs
      password: oRD$Fq@i5jE87he
      authentication-database: admin


  kafka:
    consumer:
      bootstrap-servers: 192.168.4.33:9092
      group-id: kafka_logs
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: logs-events,events
    producer:
      bootstrap-servers: 192.168.4.33:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: KAFKA-LOGS-ZERVICES
  client:
    fetch-registry: false
    register-with-eureka: false


logging:
  level:
    org:
      hibernate:
        type: trace
  file:
    name: C:/elk/spring-boot-elk.log

bcbg:
  rutaReportes: classpath:reportes/
  rutaImagenes: classpath:imagenes/

