app:
  msdb:
    jdbcUrl: jdbc:sqlserver://192.10.10.3:1433;databaseName=DB_SEGURIDAD;
    username: sa
    password: bcbg@2007
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dialect: org.hibernate.dialect.SQLServer2012Dialect
  msdbrrhh:
    jdbcUrl: jdbc:sqlserver://192.10.10.3:1433;databaseName=DB_RECURSOS_HUMANOS;
    username: sa
    password: bcbg@2007
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dialect: org.hibernate.dialect.SQLServer2012Dialect
  msdbdatabcbg:
    jdbcUrl: jdbc:sqlserver://192.10.10.3:1433;databaseName=DATA_BCBG;
    username: sa
    password: bcbg@2007
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dialect: org.hibernate.dialect.SQLServer2012Dialect
  msdbtransaction:
    jdbcUrl: jdbc:sqlserver://192.168.4.32:1433;databaseName=db_despacho
    username: sa
    password: bcbg@2007
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dialect: org.hibernate.dialect.SQLServer2012Dialect

bcbg:
  rutaArchivos: C:/archivos/tramites/
  rutaFirmaElectronica: C:/archivos/firmasElectronicas/
  urlZull: http://127.0.0.1:8720/
  urlWeb: http://127.0.0.1:8089/
  urlDinardap: http://200.124.246.174:8785/api/dinardap/aplicacion/origami/persona/identificacion/
  usuarioDinardap: adminVentanilla
  claveDinardap: NKPCSQ10@PROPIEDAD
  rutaReportes: C:/origamibcbg/services/origami-ws-bcbg/reportes/
  rutaImagenes: C:/origamibcbg/services/origami-ws-bcbg/imagenes/
  keyFiles: 12345

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
